### ISSUE TITLE
.t7 caption files

### ISSUE THREAD

**Issue by YangYang** [naver-ai/pcme#1]
I'm already following the readme to download the CUB dataset, but captions in there are not suitable for this code.
Because of the captions file type is .t7 not .txt.

**Comment by SanghyukChun** [comment]
@YangYang 
Hi, thanks for your question. Could you provide a more detailed log?
I have confirmed that the following command works for my environment
```
python train_cub.py ./config/cub/pcme_cub.yaml --dataset_root <dataset_root> --caption_root <caption_root>/cvpr2016_cub/text_c10
```

Note that, `cvpr2016_cub/text_c10` looks like this:
```
├── 001.Black_footed_Albatross.t7                       # t7 file you mentioned (not used by my code)
├── 001.Black_footed_Albatross                          # per-instance caption data used by my code
│   ├── Black_Footed_Albatross_0001_796111.h5           # not used by my code
│   ├── Black_Footed_Albatross_0001_796111.txt          # actual txt file loaded by my code
│   ├── Black_Footed_Albatross_0002_55.h5
│   ├── Black_Footed_Albatross_0002_55.txt
...
```

**Comment by YangYang** [comment]
Yes, the composition of `cvpr2016_cub/text_c10` is exactly what you said.
The reason I can't run this code is **the image name doesn't match the caption name**.
According to the [link](http://www.vision.caltech.edu/visipedia/CUB-200.html) you gave to the image, I could get:
`images/001.Black_footed_Albatross`
```
  ├── Black_footed_Albatross_0001_2950163169.jpg                    
  ├── Black_footed_Albatross_0002_2293084168.jpg 
 ...
```
However, in the [caption](https://github.com/reedscot/cvpr2016), the `cvpr2016_cub/text_c10/001.Black_footed_Albatross` is contains:
```
  ├── Black_Footed_Albatross_0001_796111.txt
  ├── Black_Footed_Albatross_0002_55.txt
 ...
```

**Comment by sawant-nidhish** [comment]
@SanghyukChun Sir, Firstly Thank You for the briliant work! Even I am facing the same problem as @YangYang.

> Yes, the composition of `cvpr2016_cub/text_c10` is exactly what you said.
> The reason I can't run this code is **the image name doesn't match the caption name**.
> According to the [link](http://www.vision.caltech.edu/visipedia/CUB-200.html) you gave to the image, I could get:
> `images/001.Black_footed_Albatross`
> 
> ```
>   ├── Black_footed_Albatross_0001_2950163169.jpg                    
>   ├── Black_footed_Albatross_0002_2293084168.jpg 
>  ...
> ```
> 
> However, in the [caption](https://github.com/reedscot/cvpr2016), the `cvpr2016_cub/text_c10/001.Black_footed_Albatross` is contains:
> 
> ```
>   ├── Black_Footed_Albatross_0001_796111.txt
>   ├── Black_Footed_Albatross_0002_55.txt
>  ...
> ```

**Comment by SanghyukChun** [comment]
@YangYang @sawant-nidhish 
Oh, I see. Thanks for your detailed reports!
I will take a look into the issue, and revise the code as soon as possible.

**Comment by YangYang** [comment]
@SanghyukChun 
Thank you for your attention!
I will wait patiently for your reply.

**Comment by SanghyukChun** [comment]
@YangYang @sawant-nidhish 
Aha, I found that the link for the CUB dataset is wrong.
I used CUB-200-2011, the extended version, but the link is the 2010 version.
Please re-download the dataset in http://www.vision.caltech.edu/visipedia/CUB-200-2011.html
I just revised the README document

Thanks for your questions!
