### ISSUE TITLE
how to get instances_train2014.json

### ISSUE THREAD

**Issue by gzwo-O** [naver-ai/pcme#5]
Hi, Thanks for your great work. But I want to know how to get instances_train2014.json ? I am looking forward to your reply.

**Comment by SanghyukChun** [comment]
Hi,
you can find the full annotations from the official website (https://cocodataset.org/#download)
Just download "2014 Train/Val annotations [241MB]"(or http://images.cocodataset.org/annotations/annotations_trainval2014.zip), and unzip:

```
$ wget http://images.cocodataset.org/annotations/annotations_trainval2014.zip
--2022-03-22 22:52:05--  http://images.cocodataset.org/annotations/annotations_trainval2014.zip
Resolving images.cocodataset.org (images.cocodataset.org)... 52.216.147.100
Connecting to images.cocodataset.org (images.cocodataset.org)|52.216.147.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 252872794 (241M) [application/zip]
Saving to: ‘annotations_trainval2014.zip’

annotations_trainval2014.zip                                        100%[===================================================================================================================================================================>] 241.16M  3.86MB/s    in 64s

2022-03-22 22:53:10 (3.75 MB/s) - ‘annotations_trainval2014.zip’ saved [252872794/252872794]

$ unzip annotations_trainval2014.zip
Archive:  annotations_trainval2014.zip
  inflating: annotations/instances_train2014.json
  inflating: annotations/instances_val2014.json
  inflating: annotations/person_keypoints_train2014.json
  inflating: annotations/person_keypoints_val2014.json
  inflating: annotations/captions_train2014.json
  inflating: annotations/captions_val2014.json

$ ls -l annotations/instances_train2014.json
-rw-rw-r--  1 user  staff  332556225 Sep  2  2017 annotations/instances_train2014.json
```

**Comment by gzwo-O** [comment]
Thank you very much for your quick reply, my problem has been solved

**Comment by gzwo-O** [comment]
Well, I have another question, when in the validation and test stage, whether I need instance_annFile?

**Comment by SanghyukChun** [comment]
`instance_annFile` is only required for measuring our new evaluation metric, PMRP (Plausible Matched R-Precision).
You can plot PMRP by epochs if you want, but if you do not want to measure PMRP, but only Recall@K, you can omit `instance_annFile` during the whole pipeline.
I only tested PMRP after finishing the whole pipeline, when I develop this method
