### ISSUE TITLE
how to get the trainval35k coco dataset

### ISSUE THREAD

**Issue by shiqubianbuhui** [naver-ai/pcme#6]
That is a great work. I want to know how to download or get trainval35k about coco dataset. Thank you very much.

**Comment by SanghyukChun** [comment]
Please check the official website
https://cocodataset.org/#download

**Comment by shiqubianbuhui** [comment]
Thank you for your reply.I have seen this official website.I want to know what the trainval35k dataset consists of. Is it all 2014train dataset plus all 2014val dataset?  Thank you very much.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Sanghyuk ***@***.***> |
| Date | 01/05/2023 13:48 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [naver-ai/pcme] how to get the trainval35k coco dataset (Issue #6) |

Please check the official website
https://cocodataset.org/#download

**Comment by SanghyukChun** [comment]
@shiqubianbuhui 
You are correct. When we use COCO dataset for image-caption tasks (e.g., cross-modal retrieval, image captioning), we use a different train/val split from the official train/val split. COCO Caption val split is a subset of the 2014val, and the remaining data points are used for training set.

Please check the following paper if you are interested in
https://arxiv.org/abs/1707.05612
