### ISSUE TITLE
apex version

### ISSUE THREAD

**Issue by hellerguyh** [naver-ai/pcme#7]
Thank you for the excellent work

Could you kindly provide more details on the specific apex version used (commit id)?
The installation guide suggests cloning and installing apex, but it seems that the latest apex version is incompatible with the torch version defined in the requirements file (1.2.0).

**Comment by SanghyukChun** [comment]
Hello, you can use the official docker from dockerhub for reproducing my environment
```
docker pull sanghyukchun/pcme:torch1.2-apex-dali
```
https://hub.docker.com/layers/sanghyukchun/pcme/torch1.2-apex-dali/images/sha256-cd64cd5dcb06f8036e7d531bb9549d00a67005384fa7aa2b2e55ca773a7af2f0?context=explore

Also, when I checked `pip freeze | grep apex`
I got `apex==0.1`

Hope this answer can help you

**Comment by SanghyukChun** [comment]
BTW, you can omit apex if you do not use the FP16 option. Just set `use_fp16: False` from the configuration
https://github.com/naver-ai/pcme/blob/main/config/coco/pcme_coco.yaml#L61

or, simply
```
python train.py <default options> --train__use_fp16 0
```

**Comment by hellerguyh** [comment]
Appreciate your assistance! 
After some experimentation, I found that using torch==1.8.0+cu111, torchvision=0.9.0+cu111, and torchtext==0.5.0 resolves the issue. Upgrading to this version of torch enabled integration with apex, although using the --train__use_fp16 option also provided a viable solution. The specific apex commit id that worked for me was ae75763.

On another note, I recommend adding pyyaml==5.4.1 to the requirements file. Newer versions of pyyaml alter the API, making them incompatible with the project code.
